name: "Security Scan"

on:
  pull_request:
  schedule:
    - cron: 25 1 * * 1

jobs:
  gosec:
    runs-on: ubuntu-latest
    # gosec is regularly broken and reporting false positives, don't let it interfere
    continue-on-error: true
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@v2
      - uses: securego/gosec@master
        with:
          # we let the report trigger content trigger a failure using the GitHub Security features.
          args: '-no-fail -fmt sarif -out results.sarif -tags fuzz ./...'
      - uses: github/codeql-action/upload-sarif@v1
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: results.sarif
